### ISSUE TITLE
pip又用不了了

### ISSUE THREAD

**Issue by mike-unk** [zhanyong-wan/dongbei#88]
```
C:\Users\******>python -m pip install dongbei-lang
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting dongbei-lang
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b3/4a/1fce9d7ffad31068a3188aa5ea0d1df1b4e552ce2d94173bdda2703eb385/dongbei-lang-0.0.5.tar.gz (15.6MB)
     |████████████████████████████████| 15.6MB 261kB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\homepc\\AppData\\Local\\Temp\\pip-install-rtf6dlxt\\dongbei-lang\\setup.py'"'"'; __file__='"'"'C:\\Users\\homepc\\AppData\\Local\\Temp\\pip-install-rtf6dlxt\\dongbei-lang\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\homepc\AppData\Local\Temp\pip-install-rtf6dlxt\dongbei-lang\
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\homepc\AppData\Local\Temp\pip-install-rtf6dlxt\dongbei-lang\setup.py", line 3, in <module>
        setup()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 137, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py", line 701, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\config.py", line 116, in parse_configuration
        options.parse()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\config.py", line 426, in parse
        section_parser_method(section_options)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\config.py", line 616, in parse_section_entry_points
        self['entry_points'] = parsed
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\config.py", line 174, in __setitem__
        raise KeyError(option_name)
    KeyError: 'entry_points'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by zhanyong-wan** [comment]
试试 pip3 ？

瞅瞅 https://github.com/zhanyong-wan/dongbei#%E5%AE%89%E8%A3%85

**Comment by mike-unk** [comment]
@zhanyong-wan 我Windows，只安装了Anaconda3 (Python 3.7.4)，不能用pip3.

**Comment by zhanyong-wan** [comment]
这个请哪位用 Windows 的大哥大姐帮忙看看？

**Comment by harrywang** [comment]
@mike-unk 试试我写的这个？https://github.com/harrywang/self-contained-project/wiki/How-to-setup-Python-3-virtual-environment-on-Windows-10

**Comment by mike-unk** [comment]
刚刚安装原版python，好了
